CREATE TABLE IF NOT EXISTS form_progress (
    token CHAR(36) PRIMARY KEY,
    form_data JSON,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);