CREATE TABLE IF NOT EXISTS form_progress (
    token UUID PRIMARY KEY,
    form_data JSONB,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);